### ISSUE TITLE
[WotLK] no DoT duration on nameplates and unitframes

### ISSUE THREAD

**Issue by stva23** [tukui-org/Tukui#44]
After commit 8a1eaf1a047d235e989b1f2a81aaa71aec2dddcc remaining dot time is not displayed on the nameplates or unitframes.

**Comment by tukz** [comment]
Should be fixed.

**Comment by stva23** [comment]
Sry, but it isnt fixed. Not in the commit when this was closed, nor with the latest commit.
